services:
  - type: web
    name: url-shortener
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You will enter your MongoDB Atlas URI in the Render Dashboard
      - key: REDIS_URI
        fromService:
          type: redis
          name: url-shortener-redis
          property: connectionString

  - type: redis
    name: url-shortener-redis
    ipAllowList: [] # Allows access only from other services in this Render account
    plan: free # Change this to a paid plan if needed for production
